- name: "Setup computer"
  hosts: localhost
  vars:
    username: giovannifoletto
    hostname: fedora
    # possible tags:
    # - sync => add Synchronization functionality and start copying the home directory to another computer
    # to test better, deactivated
    # - migration => this is maybe better, organize all tasks inside this to make a backup and then sync locally or recover from backup
    # - optional => install script/programs that are optional
    borg_username: borg
    borg_server: 192.168.1.1
    borg_repo_location: /data/{{ username }}-repo
    apktool_version: 2.10.0
    burp_version: 2024.9.5
    jd_gui_version: 1.6.6
  tasks:

  - name: Update/Upgrade
    ansible.builtin.dnf5:
      name: "*"
      state: latest
    become: yes
    become_method: sudo

  - name: Install things to make fedora usable
    ansible.builtin.import_tasks: tasks/things_to_do_after_installing_fedora.yml
    
  - name: ZSH/ZIM installation
    ansible.builtin.import_tasks: tasks/install_zim.yml

  - name: Install VSCODE
    ansible.builtin.import_tasks: tasks/install_vscode.yml

  - name: Install Docker
    ansible.builtin.import_tasks: tasks/install_docker.yml

  - name: Install go and rust toolchain
    ansible.builtin.import_tasks: tasks/install_toolchain.yml
  
  - name: Install security tools
    ansible.builtin.import_tasks: tasks/install_tools.yml
  
  - name: Synchronization tasks
    ansible.builtin.import_tasks: tasks/sync_tasks.yml
    tags: sync

  - name: Setup borgbackup and borgmatic
    ansible.builtin.import_tasks: tasks/borg_backup.yml
    tags: sync
  
