- name: "Setup computer"
  hosts: localhost
  connection: local 
  vars_files:
    - config.yml
  tasks:
    - name: Update/Upgrade
      ansible.builtin.dnf:
        name: "*"
        state: latest
      become: yes
      become_method: sudo
      when: update_all

    - name: Install things to make fedora usable
      ansible.builtin.include_tasks: tasks/things_to_do_after_installing_fedora.yml
      
    - name: ZSH/ZIM installation
      ansible.builtin.include_tasks: tasks/install_zim.yml

    - name: Install misc software
      ansible.builtin.include_tasks: tasks/misc.yml
      when: misc_software

    - name: Install repo from config
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        baseurl: "{{ item.url }}"
        description: "{{ item.name }}"
      loop: "{{ repo_to_add }}"
      when: (repo_to_add | length) > 0
      become: true
      become_user: root

    - name: Install softwares from config
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      become: true
      become_user: root

    - name: Install code toolchain
      ansible.builtin.include_tasks: tasks/install_toolchain.yml
    
    - name: Install from Github
      ansible.builtin.include_tasks: tasks/download_from_link.yml
      loop: "{{ download_from_link }}"
      when: (download_from_link | length) > 0
    
    - name: Install kubernetes
      ansible.builtin.include_tasks: tasks/kubectl.yml

    - name: Add configuration
      ansible.builtin.lineinfile:
        path: "{{ item.file }}"
        line: "{{ item.line }}"
      loop: "{{ files_add_lines }}"

    # - name: Install security tools
    #   ansible.builtin.include_tasks: tasks/install_tools.yml  
    
    # - name: Setup SSH and GPG
    #   ansible.builtin.include_tasks: tasks/crypto_setup.yml
    #   tags: todo

    # - name: Synchronization tasks
    #   ansible.builtin.include_tasks: tasks/sync_tasks.yml
    #   tags: sync

    # - name: Setup borgbackup and borgmatic
    #   ansible.builtin.include_tasks: tasks/borg_backup.yml
    #   tags: sync
