- name: Check if borg is installed
  ansible.builtin.dnf:
    name: 
      - borgbackup
      - borgmatic
    state: latest

- name: Installing borgmatic configuration
  ansible.builtin.template:
    src: 'templates/borgmatic.j2'
    dest: /etc/borgmatic/config.yml

- name: Install Pika Backup
  community.general.flatpak:
    name: org.gnome.World.PikaBackup
    method: user
    state: present

