---
- name: Download binary
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
    mode: "0755"

- name: Install executable in /usr/local/bin
  ansible.builtin.copy:
    dest: "/usr/local/bin/{{ item.name }}"
    src: "/tmp/{{ item.name }}"
    mode: "0755"
  become: true
  become_user: root
