---
- name: Install vscode gpg
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Update VsCode repo file
  ansible.builtin.template:
    src: 'templates/vscode.j2'
    dest: /etc/yum.repos.d/vscode.repo
    
- name: Install Packages
  ansible.builtin.dnf5:
    name: code
    state: latest