---
- name: Get ZSH
  tags: alreadyzim
  ansible.builtin.dnf:
    name: 
    - curl
    - wget
    - zsh
    state: present
  become: true
  become_method: sudo

- name: Check if ZIM is already present
  ansible.builtin.stat:
    path: "/home/{{ config.username }}/.zim"
  register: check_zim

- name: Install ZIM
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh"
  when: not check_zim.stat.exists

- name: Reconfigure ZIM
  when: not check_zim.stat.exists
  block:
    - ansible.builtin.replace:
        path: /home/{{ config.username }}/.zimrc
        regexp: "zmodule asciiship"
        replace: "zmodule prompt-pwd"
    - ansible.builtin.lineinfile:
        line: "zmodule gitster"
        state: present

- name: Install new packages for ZIM
  when: not check_zim.stat.exists
  ansible.builtin.shell: zimfw install
  args:
    executable: /bin/zsh

- name: Update/Upgrade ZIM
  when: not check_zim.stat.exists
  ansible.builtin.shell: zimfw upgrade
  args:
    executable: /bin/zsh

- name: Update user
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: "{{ config.username }}"
    shell: /bin/zsh

# download font
- name: Install Jetbrains Font
  when: fonts is defined
  block:
    - name: Download font zip
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
        dest: /home/{{ config.username }}/Downloads/hacks.zip

    # - name: Unzip the fonts
    #   ansible.builtin.unarchive:
