---
- name: Get ZSH
  tags: alreadyzim
  ansible.builtin.dnf:
    name: 
    - curl
    - wget
    - zsh
    state: present
  become: true
  become_method: sudo

- name: Install ZIM
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh"
  tags: alreadyzim

- name: Reconfigure ZIM
  tags: alreadyzim
  ansible.builtin.replace:
    path: /home/{{ username }}/.zimrc
    regexp: "zmodule asciiship"
    replace: "zmodule prompt-pwd\nzmodule gitster"

- name: Install new packages for ZIM
  tags: alreadyzim
  ansible.builtin.shell: zimfw install
  args:
    executable: /bin/zsh

- name: Update/Upgrade ZIM
  tags: alreadyzim
  ansible.builtin.shell: zimfw upgrade
  args:
    executable: /bin/zsh

- name: Update user
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh

# download font
- name: Install Jetbrains Font
  tags: todo
  block:
    - name: Download font zip
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
        dest: /home/{{ username }}/Downloads/hacks.zip

    # - name: Unzip the fonts
    #   ansible.builtin.unarchive:
