---
- name: Get ZSH
  become: true
  become_method: sudo
  ansible.builtin.dnf5:
    name: 
    - curl
    - wget
    - zsh
    state: present

- name: Install ZIM
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh"

- name: Reconfigure ZIM
  ansible.builtin.replace:
    path: '/home/{{username}}/.zimrc'
    regexp: "zmodule asciiship"
    replace: "zmodule prompt-pwd\nzmodule gitster"

- name: Install new packages for ZIM
  ansible.builtin.shell: "zimfw install"

- name: Update/Upgrade ZIM
  ansible.builtin.shell: "zimfw upgrade"

- name: Update user
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh

# download font
# - name: Install Jetbrains Font
  
