# Openconnect, openvpn, wireguard, google-chrome
- name: Install miscellaneus packages
  ansible.builtin.dnf:
    name:
      - openvpn
      - wireguard-tools
      - google-chrome-stable
      - btrfs-assistant
      - curl
      - wget
      - '@Multimedia'
    state: present
  become: true
  become_method: sudo

- name: Optional tailscale
  tags: optional-tailscale
  ansible.builtin.dnf:
    name:
      - tailscale
    state: present
    become: true
    become_method: sudo

- name: Install VsCode
  block:
    - name: Install vscode gpg
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
      become: true
      become_method: sudo

    - name: Update VsCode repo file
      ansible.builtin.template:
        src: 'templates/vscode.j2'
        dest: /etc/yum.repos.d/vscode.repo
      become: true
      become_method: sudo

    - name: Install Packages
      ansible.builtin.dnf:
        name: code
        state: latest
      become: true
      become_method: sudo

- name: Install docker
  tags: docker-installed
  block:
    - name: Get commodity script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'
      
    - name: Run commodity script
      ansible.builtin.command: bash -c /tmp/get-docker.sh
      become: true
      become_method: sudo

