# Following https://itsfoss.com/things-to-do-after-installing-fedora/

- name: Change dnf configuration for more concurrent download
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    state: present
    line: max_parallel_downloads=10
  become: true
  become_method: sudo

- name: Change dnf configuration for 'fastermirror'
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    state: present
    line: fastestmirror=true
  become: true
  become_method: sudo

- name: Installing resources, sudo block
  become: true
  become_method: sudo
  block:
  - name: Enable the RPM Fusion repository
    ansible.builtin.dnf5:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      state: present
      update_cache: true

  - name: Activate rpm-fusion-non-free
    ansible.builtin.dnf5:
      name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
      state: present
      update_cache: true

  - name: Install codec plugins
    ansible.builtin.dnf5:
      name:
        - gstreamer1-plugins-bad{bad-\*,good-\*,base} 
        - gstreamer1-plugin-openh264
        - gstreamer1-libav 
      state: present
  
  - name: Remove gstreamer1-plugins-bad-free-devel
    ansible.builtin.dnf5:
      name: gstreamer1-plugins-bad-free-devel
      state: absent
  
  - name: Install lame\*
    ansible.builtin.dnf5:
      name: lame\*
      state: present
  
  - name: Remove lame-devel
    ansible.builtin.dnf5:
      name: lame-devel
      state: absent
    
  - name: Install Multimedia
    ansible.builtin.dnf5:
      name: ''

- name: Set new hostname
  ansible.builtin.hostname:
    name: '{{ hostname }}'

- name: Install gnome-tweaks
  ansible.builtin.dnf5:
    name:
    - gnome-tweaks
    - gnome-extensions-app
    state: present
  become: true
  become_method: sudo
